dist:     focal
sudo:     required  # используем Virtual Machine (а не Docker container)

language: c

os:
  - linux

compiler:
  - gcc

install:
  - sudo apt-get install valgrind
  - sudo pip3 install cpplint
  - sudo apt install cppcheck

before_script:
  - cd "${TRAVIS_BUILD_DIR}"/HW_2/tests
  - bash generate_tests.sh
  - cd ..
  - mkdir build && cd build
  - cmake ..
  - make clean && make
  - cd ..
  - cd ..

script:
  - cpplint --extensions=c,cpp HW_2/project/include/one/* HW_2/project/include/multi/* HW_2/project/src/one/* HW_2/project/src/multi/* HW_2/tests/*.cpp
#  - ./HW_2/build/TEST
  - valgrind --track-origins=yes --child-silent-after-fork=yes --leak-check=full ./HW_2/build/TEST_VALGRIND
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./HW_2/project
  - cd "${TRAVIS_BUILD_DIR}"/HW_2/project
  - bash <(curl -s https://codecov.io/bash)